-- CreateTable
CREATE TABLE "Logging" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "SYMBOL" TEXT NOT NULL,
    "INVESTMENT" REAL NOT NULL,
    "GENERATIONDATE" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "Opening_Average" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "SYMBOL" TEXT NOT NULL,
    "AVERAGE" REAL NOT NULL,
    "GENERATIONDATE" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "Results" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "QUERY" TEXT NOT NULL,
    "SYMBOL" TEXT NOT NULL,
    "NUMBERCOINS" REAL NOT NULL,
    "PROFIT" REAL NOT NULL,
    "GROWTHFACTOR" REAL NOT NULL,
    "LAMBOS" REAL NOT NULL,
    "INVESTMENT" REAL NOT NULL,
    "GENERATIONDATE" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
